import { Tooltip } from '../components/Tooltip'
import { useQuery } from '@tanstack/react-query'

const KINDS = ['star', 'unstar', 'follow', 'unfollow']

// `<slug>-<kind>.png` → [slug, kind]
function parse(name: string): [string, string] {
  const stem = name.replace(/\.png$/, '')
  const i = stem.lastIndexOf('-')
  return [stem.slice(0, i), stem.slice(i + 1)]
}

export default function Icons() {
  const { data, isLoading, error } = useQuery({
    queryKey: ['icons'],
    queryFn: () => fetch('/icons/manifest.json').then(r => r.json() as Promise<{ files: string[] }>),
  })
  if (isLoading) return <p className="dim">loading…</p>
  if (error || !data) return <p className="error">{String(error)}</p>

  const bySlug = new Map<string, Map<string, string>>()
  for (const f of data.files) {
    const [slug, kind] = parse(f)
    if (!bySlug.has(slug)) bySlug.set(slug, new Map())
    bySlug.get(slug)!.set(kind, f)
  }
  const kinds = KINDS.filter(k => [...bySlug.values()].some(m => m.has(k)))

  return (
    <div className="icons">
      <p>
        Retired per-message Slack avatars: org logo (or the <code>gh</code> mark fallback) + event-kind badge,
        posted via <code>chat.postMessage</code> <code>icon_url</code>. Messages are now actor-voiced — the
        actor's GitHub avatar, with the kind carried by a ⭐/💔/🔔/🔕 verb in the sender line.
        Generated by <code>scripts/gen-pfp.py icons</code>.
      </p>
      <table>
        <thead>
          <tr><th></th>{kinds.map(k => <th key={k}>{k}</th>)}</tr>
        </thead>
        <tbody>
          {[...bySlug.entries()].map(([slug, m]) => (
            <tr key={slug}>
              <th>{slug}</th>
              {kinds.map(k => {
                const f = m.get(k)
                return (
                  <td key={k}>
                    {f && <Tooltip tip={f}><a href={`/icons/${f}`}><img src={`/icons/${f}`} alt={f} /></a></Tooltip>}
                  </td>
                )
              })}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}
